version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./API/uploads:/app/API/uploads  
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017

  mongo:
    image: mongo
    container_name: tinpic_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
